#Minecraft server properties
#Sun May 04 15:03:33 PDT 2025
# Server Info
server-name=Pancake Realm
motd=§6Pancake Realm §7- §f1.12.2 Eaglercraft §8| §aNetherite + Mace!
max-players=100

# Cracked / Offline mode
online-mode=false

# Basic performance
view-distance=8
difficulty=normal 
gamemode=survival
spawn-protection=16
pvp=true

# Eaglercraft recommended settings
allow-nether=true
allow-end=true

max-world-size=29999984
resource-pack=https://download.mc-packs.net/pack/cac32fcb814965adc2894521a347b3c01155c4f8.zip
resource-pack-prompt=§6Pancake Realm §7- Accept the resource pack for custom Mace!
